schema_version = "1.0.0"

id = "amp_animate_pro"
version = "0.25.30922"
name = "AniMate - AniMatePro Core"
tagline = "1.0 Beta - Supercharge your Animation Workflow"
maintainer = "not that NDA <nda@notthatnda.com>"
website = "https://linktr.ee/notthatnda"

type = "add-on"
tags = ["Animation"]
blender_version_min = "4.1.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = ["2022-2025 Nacho (not that NDA) de Andres"]

[permissions]
files = "Access to filesystem to save and load add-on preferences"
network = "Addon updates"
clipboard = "Copy and paste UI configuration and add-on preferences"